version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: quora
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
    ports:
      - "5433:5432"  # Maps host port 5433 to container port 5432
    volumes:
      - db_data:/var/lib/postgresql/data

  # This is your backend service
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  # This is your frontend service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    ports:
      - "8080:8080"
    depends_on:
      - web

  # Nginx service to act as a reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80" # Expose Nginx on host port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount the Nginx configuration file
    depends_on:
      - web # Nginx depends on the backend
      - client # Nginx depends on the frontend

volumes:
  db_data: